# Generated by Django 4.0.1 on 2022-04-29 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
    ]
